### ISSUE TITLE
Fetch transaction history failed. Network error

### ISSUE THREAD

**Issue by DavidDerhy** [ontio/OWallet#57]
There is a problem when I log in to my wallet (Windows version), the balance is 0 ONT and 0 ONG and I am not able to see my coins anymore or previous transactions. 

An error message is popping: **"Fetch transaction history failed. Network error."**

![image](https://user-images.githubusercontent.com/15603952/44294167-2afe4800-a293-11e8-94e5-809443be8be3.png)

**Comment by shogun0101** [comment]
Same issue here. I also noticed on my network I can't reach ont blockchain explorer but I can outside network.

**Comment by shogun0101** [comment]
Do you mean external IP?

**Comment by shogun0101** [comment]
47.187.102.31 is my external

**Comment by DavidDerhy** [comment]
Thx, in fact, when I changed the network it worked. 

I don't know what you mean by export IP but if you meant external IP here is mine: 80.12.41.171

**Comment by shogun0101** [comment]
David what did you change on network?

**Comment by DavidDerhy** [comment]
I simply used another operator network and it worked for me.

**Comment by matthieuvandiepen** [comment]
Hi, I also have this problem.

My IP

77.168.20.209

And I guess this is usefull

C:\Users\BucketBrigade>tracert explorer.ont.io

Tracing route to explorer.ont.io [104.215.199.197]
over a maximum of 30 hops:

  1     2 ms     1 ms     1 ms  mijnmodem.kpn.home [192.168.2.254]
  2     5 ms     4 ms     5 ms  195.190.228.188
  3    10 ms     9 ms     9 ms  nl-rt2-pice-ir01.kpn.net [80.249.208.89]
  4     9 ms     8 ms     8 ms  ams-ix-2.microsoft.com [80.249.209.21]
  5   188 ms   187 ms   187 ms  be-72-0.ibr02.amb.ntwk.msn.net [104.44.9.138]
  6   189 ms   187 ms   188 ms  104.44.16.41
  7   187 ms   187 ms   189 ms  be-1-0.ibr02.par21.ntwk.msn.net [104.44.7.214]
  8   185 ms   184 ms   184 ms  be-3-0.ibr02.mrs20.ntwk.msn.net [104.44.7.49]
  9   123 ms   123 ms   122 ms  ae20-0.bom30-96cbe-1b.ntwk.msn.net [104.44.20.130]
 10   124 ms   123 ms   124 ms  ae0-0.bom30-96cbe-1a.ntwk.msn.net [104.44.227.186]
 11   123 ms   123 ms   124 ms  ae0-0.co2-96lsr-2.ntwk.msn.net [104.44.226.125]
 12   192 ms   192 ms   193 ms  ae22-0.sge-96cbe-1b.ntwk.msn.net [198.206.164.99]
 13   186 ms   186 ms   187 ms  ae38-0.icr02.sg2.ntwk.msn.net [104.44.236.146]
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

**Comment by xiaomin49** [comment]
Thank you for your helpful information . We've fixed network issues . Please check it up. Just let us know if you have any question.

**Comment by matthieuvandiepen** [comment]
Hi, still the same problem, I send you new traces. Something changed, first the problem was after hop 13, now it is after hop 11.

I sent you 3 traces:

C:\Users\BucketBrigade>tracert explorer.ont.io

Tracing route to explorer.ont.io [104.215.199.197]
over a maximum of 30 hops:

  1     1 ms     1 ms    <1 ms  mijnmodem.kpn.home [192.168.2.254]
  2     4 ms     4 ms     5 ms  195.190.228.188
  3     *        *        *     Request timed out.
  4     9 ms    10 ms     8 ms  ams-ix-2.microsoft.com [80.249.209.21]
  5   192 ms   190 ms   191 ms  be-72-0.ibr02.amb.ntwk.msn.net [104.44.9.138]
  6   206 ms   204 ms     *     104.44.16.41
  7    30 ms    21 ms    21 ms  ae120-0.icr01.par30.ntwk.msn.net [104.44.11.236]
  8    29 ms    22 ms    21 ms  ae22-0.pra-96cbe-1a.ntwk.msn.net [104.44.236.88]
  9   133 ms   134 ms   132 ms  ae5-0.bom02-96cbe-1a.ntwk.msn.net [198.206.164.52]
 10   199 ms   199 ms   198 ms  ae22-0.sge-96cbe-1b.ntwk.msn.net [198.206.164.99]
 11   193 ms   189 ms   188 ms  ae38-0.icr02.sg2.ntwk.msn.net [104.44.236.146]
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

C:\Users\BucketBrigade>tracert explorer.ont.io

Tracing route to explorer.ont.io [104.215.199.197]
over a maximum of 30 hops:

  1     4 ms     *        2 ms  mijnmodem.kpn.home [192.168.2.254]
  2     7 ms     5 ms     5 ms  195.190.228.188
  3     *        *        9 ms  nl-rt2-pice-ir01.kpn.net [80.249.208.89]
  4    16 ms    12 ms     9 ms  ams-ix-2.microsoft.com [80.249.209.21]
  5   192 ms   191 ms   190 ms  be-72-0.ibr02.amb.ntwk.msn.net [104.44.9.138]
  6   205 ms     *      205 ms  104.44.16.41
  7    23 ms    21 ms    25 ms  ae120-0.icr01.par30.ntwk.msn.net [104.44.11.236]
  8    21 ms    21 ms    22 ms  ae22-0.pra-96cbe-1a.ntwk.msn.net [104.44.236.88]
  9   134 ms   132 ms   132 ms  ae5-0.bom02-96cbe-1a.ntwk.msn.net [198.206.164.52]
 10   202 ms   203 ms   202 ms  ae22-0.sge-96cbe-1b.ntwk.msn.net [198.206.164.99]
 11   193 ms   190 ms   191 ms  ae38-0.icr02.sg2.ntwk.msn.net [104.44.236.146]
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

C:\Users\BucketBrigade>tracert explorer.ont.io

Tracing route to explorer.ont.io [104.215.199.197]
over a maximum of 30 hops:

  1     2 ms     1 ms     5 ms  mijnmodem.kpn.home [192.168.2.254]
  2    94 ms     5 ms     7 ms  195.190.228.188
  3     *       11 ms     9 ms  nl-rt2-pice-ir01.kpn.net [80.249.208.89]
  4    12 ms    11 ms    10 ms  ams-ix-2.microsoft.com [80.249.209.21]
  5   201 ms   203 ms   203 ms  be-72-0.ibr02.amb.ntwk.msn.net [104.44.9.138]
  6   204 ms   205 ms   205 ms  104.44.16.41
  7    27 ms    23 ms    29 ms  ae120-0.icr01.par30.ntwk.msn.net [104.44.11.236]
  8    23 ms    20 ms    25 ms  ae22-0.pra-96cbe-1a.ntwk.msn.net [104.44.236.88]
  9   133 ms   151 ms   134 ms  ae5-0.bom02-96cbe-1a.ntwk.msn.net [198.206.164.52]
 10   215 ms   199 ms   198 ms  ae22-0.sge-96cbe-1b.ntwk.msn.net [198.206.164.99]
 11   198 ms   206 ms   217 ms  ae38-0.icr02.sg2.ntwk.msn.net [104.44.236.146]
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

**Comment by xiaomin49** [comment]
Sure , Thanks for you info . We'll look into the case .

**Comment by isaacfufu** [comment]
I also have the same issue as Shogun0101.

**Comment by branners** [comment]
I am having this issue too

**Comment by DavidDerhy** [comment]
I still have the same issue when I'm using my wifi but I can see them when I do an Internet connection-sharing from my phone.

**Comment by shogun0101** [comment]
The network is working for me now on v0.8.3. Can also see blockchain explorer now! YAY! Thank You!

**Comment by DavidDerhy** [comment]
Pb fixed.Thx!

**Comment by Shirazkp** [comment]
Im having the same issue. Can someone please assist me to sort this out in a simpler way
